/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sumames.sir.ui.report;

import com.sumames.sir.Main;
import com.sumames.sir.entity.AccountGroup;
import com.sumames.sir.entity.Rent;
import com.sumames.sir.helper.AppUtil;
import com.sumames.sir.helper.TextComponentUtils;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author My pc
 */
public class AccountGroupData extends javax.swing.JPanel {
    
    private String option;
    private int recordId;
    private AccountGroup accountGroup;

    /**
     * Creates new form EmployerInput
     */
    public AccountGroupData(String option, int recordId) {
        this.option = option;
        this.recordId = recordId;
        initComponents();
        loadingData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbGroup = new javax.swing.JComboBox<>();
        tfSubGroup = new javax.swing.JTextField();

        setFont(new java.awt.Font("Noto Serif", 0, 14)); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(844, 417));

        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/buttons/6-01.png"))); // NOI18N
        btSave.setBorderPainted(false);
        btSave.setContentAreaFilled(false);
        btSave.setPreferredSize(new java.awt.Dimension(65, 23));
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(getFont());
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Kelompok");
        jLabel6.setPreferredSize(new java.awt.Dimension(25, 30));

        jLabel1.setFont(getFont());
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sub Kelompok");
        jLabel1.setPreferredSize(new java.awt.Dimension(44, 30));

        cbGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktiva Lancar", "Aktiva Tidak Lancar", "Passiva Lancar", "Passiva Tidak Lancar", "Modal", "Pendapatan", "Harga Pokok Penjualan", "Harga Pokok Produksi", "Pembelian", "Biaya Operasional", "Biaya Produksi", "Pajak", "Lainnya" }));
        cbGroup.setPreferredSize(new java.awt.Dimension(100, 30));

        tfSubGroup.setFont(getFont());
        tfSubGroup.setPreferredSize(new java.awt.Dimension(100, 30));
        TextComponentUtils.setNumericTextOnly(tfSubGroup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSubGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(cbGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSubGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

   
    

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        saveData();
    }//GEN-LAST:event_btSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfSubGroup;
    // End of variables declaration//GEN-END:variables
    
    public void loadingData() {
        if (option.equals("NEW")) {
            tfSubGroup.setText("");
        } else if (option.equals("EDIT")) {
            accountGroup = AppUtil.getService().getAccountGroupById(recordId);
            objectToForm();
        }
    }
    
   
    
    
    public void saveData() {
        if (option.equals("NEW")) {
            formToObject();
            accountGroup.setCreateDatetime(new Date());
            accountGroup.setCreateByRecordId(Main.getFrame().getLogin().getEmployeeRecordId());
            if (AppUtil.getService().save(accountGroup)) {
                msg("Save Done!");
                Main.getFrame().getTab().removeTabAt(Main.getFrame().getTab().getSelectedIndex());
            } else {
                msg("Save Failed!");
            }
        } else if (option.equals("EDIT")) {
            formToObject();
            accountGroup.setRecordId(recordId);
            accountGroup.setEditDatetime(new Date());
            accountGroup.setEditByRecordId(Main.getFrame().getLogin().getEmployeeRecordId());
            if (AppUtil.getService().save(accountGroup)) {
                msg("Save Done!");
                Main.getFrame().getTab().removeTabAt(Main.getFrame().getTab().getSelectedIndex());
            } else {
                msg("Save Failed!");
            }
        }
    }
    
    public void formToObject() {
        if (accountGroup == null) {
            accountGroup = new AccountGroup();
        }
        
        accountGroup.setAccountGroupName(cbGroup.getSelectedIndex());
        accountGroup.setAccountGroupSubName(tfSubGroup.getText());
        
    }
    
    public void objectToForm() {
        if (accountGroup != null) {
            cbGroup.setSelectedIndex(accountGroup.getAccountGroupName());
            tfSubGroup.setText(accountGroup.getAccountGroupSubName());
        }
    }
    
    private void msg(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
}
