package com.sumames.sir.ui.report;

import com.sumames.sir.ui.purchase.*;
import com.sumames.sir.Main;
import com.sumames.sir.ui.MainFrame;
import com.sumames.sir.helper.Support;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sutandi
 */
public class ReportMenu extends javax.swing.JPanel {
    /**
     * Creates new form PeopleMenu
     */
    public ReportMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroup = new javax.swing.JButton();
        btChart = new javax.swing.JButton();
        btJournal = new javax.swing.JButton();
        btLedger = new javax.swing.JButton();
        btSpending = new javax.swing.JButton();
        btIncome = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(2, 0));

        btGroup.setText("Account Group");
        btGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btGroup.setContentAreaFilled(false);
        btGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btGroupMouseExited(evt);
            }
        });
        btGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGroupActionPerformed(evt);
            }
        });
        add(btGroup);

        btChart.setText("Account Chart");
        btChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btChart.setContentAreaFilled(false);
        btChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btChartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btChartMouseExited(evt);
            }
        });
        btChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChartActionPerformed(evt);
            }
        });
        add(btChart);

        btJournal.setText("Journal");
        btJournal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btJournal.setContentAreaFilled(false);
        btJournal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btJournalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btJournalMouseExited(evt);
            }
        });
        btJournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJournalActionPerformed(evt);
            }
        });
        add(btJournal);

        btLedger.setText("Ledger");
        btLedger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btLedger.setContentAreaFilled(false);
        btLedger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLedgerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLedgerMouseExited(evt);
            }
        });
        btLedger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLedgerActionPerformed(evt);
            }
        });
        add(btLedger);

        btSpending.setText("Spending");
        btSpending.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btSpending.setContentAreaFilled(false);
        btSpending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSpendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSpendingMouseExited(evt);
            }
        });
        btSpending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSpendingActionPerformed(evt);
            }
        });
        add(btSpending);

        btIncome.setText("Income Statement");
        btIncome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btIncome.setContentAreaFilled(false);
        btIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btIncomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btIncomeMouseExited(evt);
            }
        });
        btIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncomeActionPerformed(evt);
            }
        });
        add(btIncome);
    }// </editor-fold>//GEN-END:initComponents

    private void btChartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btChartMouseEntered
        btChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btChartMouseEntered

    private void btChartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btChartMouseExited
        btChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btChartMouseExited

    private void btLedgerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLedgerMouseEntered
        btLedger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btLedgerMouseEntered

    private void btLedgerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLedgerMouseExited
        btLedger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btLedgerMouseExited

    private void btChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChartActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new AccountChartList(), "Account Chart List");
    }//GEN-LAST:event_btChartActionPerformed

    private void btLedgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLedgerActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new LedgerList(), "Ledger List");
    }//GEN-LAST:event_btLedgerActionPerformed

    private void btGroupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGroupMouseEntered
        btGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btGroupMouseEntered

    private void btGroupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGroupMouseExited
        btGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btGroupMouseExited

    private void btGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGroupActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new AccountGroupList(), "Account Group List");
    }//GEN-LAST:event_btGroupActionPerformed

    private void btJournalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJournalMouseEntered
        btJournal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btJournalMouseEntered

    private void btJournalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJournalMouseExited
        btJournal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btJournalMouseExited

    private void btJournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJournalActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new JournalList(), "Journal List");
    }//GEN-LAST:event_btJournalActionPerformed

    private void btSpendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSpendingMouseEntered
        btSpending.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btSpendingMouseEntered

    private void btSpendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSpendingMouseExited
        btSpending.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btSpendingMouseExited

    private void btSpendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSpendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSpendingActionPerformed

    private void btIncomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncomeMouseEntered
        btIncome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btIncomeMouseEntered

    private void btIncomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncomeMouseExited
        btIncome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btIncomeMouseExited

    private void btIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIncomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChart;
    private javax.swing.JButton btGroup;
    private javax.swing.JButton btIncome;
    private javax.swing.JButton btJournal;
    private javax.swing.JButton btLedger;
    private javax.swing.JButton btSpending;
    // End of variables declaration//GEN-END:variables
}
