/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sumames.sir.ui;

import com.sumames.sir.ui.renderer.GlassPanePanel;
import com.sumames.sir.Main;
import com.sumames.sir.entity.Login;
import com.sumames.sir.helper.AppUtil;
import com.sumames.sir.resources.image.LoadImages;
import com.sumames.sir.ui.renderer.ClosableTabbedPane;
import com.sumames.sir.ui.people.PeopleMenu;
import com.sumames.sir.ui.rent.RentList;
import com.sumames.sir.ui.garage.GarageList;
import com.sumames.sir.ui.purchase.PurchaseMenu;
import com.sumames.sir.helper.Support;
import com.sumames.sir.ui.access.AccessList;
import com.sumames.sir.ui.report.ReportMenu;
import java.awt.AlphaComposite;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JTabbedPane;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author Sutandi
 */
public class MainFrame extends javax.swing.JFrame {

    private final GlassPanePanel glasspane;
    private final CardLayout card;
    private final LoadImages load;
    private Login login;

    private int LoadValue;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        glasspane = new GlassPanePanel();
        setGlassPane(glasspane);
        load = new LoadImages();
        initComponents();
        getContentPane().add(LoginPanel, "card");
        card = (CardLayout) getContentPane().getLayout();
        card.show(getContentPane(), "card");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                String string = new SimpleDateFormat("HH:mm:ss").format(new Date());
                lblTime.setText(string);
                String string2 = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
                lblDate.setText(string2);
            }
        }, 0, 1000);

    }

    public Login getLogin() {
        return login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LoginPanel = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                GradientPaint paint = new GradientPaint(0, 0, new Color(250, 174, 66, 255), getWidth(), getHeight(), new Color(247, 90, 43, 255));
                Graphics2D g2 = (Graphics2D) g.create();

                g2.setPaint(paint);
                g2.fillRect(0, 0, getWidth(), getHeight());
                g2.setComposite(AlphaComposite.SrcOver.derive(1.0F));
                int x = (this.getWidth() - load.getLogo().getWidth(null)) / 2;
                int y = (this.getHeight() - load.getLogo().getHeight(null)) / 2;
                g2.drawImage(load.getLogo(), x, y, null);
                g2.dispose();

            }
        };
        LoginPan = new javax.swing.JPanel();
        lblUsernameLogin = new javax.swing.JLabel();
        tfPasswordLogin = new javax.swing.JPasswordField();
        tfUsername = new javax.swing.JTextField();
        btLogin2 = new javax.swing.JButton();
        lblPasswordLogin = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SettingPanel = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        tfServer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfPort = new javax.swing.JTextField();
        lbl_database = new javax.swing.JLabel();
        cbDatabase = new javax.swing.JComboBox<>();
        lbl_password = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btConnect = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                GradientPaint paint = new GradientPaint(0, 0, new Color(250, 174, 66, 255), getWidth(), getHeight(), new Color(247, 90, 43, 255));
                Graphics2D g2 = (Graphics2D) g.create();

                g2.setPaint(paint);
                g2.fillRect(0, 0, getWidth(), getHeight());
                g2.setComposite(AlphaComposite.SrcOver.derive(1.0F));
                g2.dispose();
            }
        };
        NavPanel = new javax.swing.JPanel();
        btLogin = new javax.swing.JButton();
        btPassword = new javax.swing.JButton();
        btSetting = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btAbout = new javax.swing.JButton();
        BodyPanel = new javax.swing.JPanel();
        LoadingBar = new javax.swing.JProgressBar();
        lblUsername = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        ProgressPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new ClosableTabbedPane();

        LoginPanel.setPreferredSize(new java.awt.Dimension(450, 150));
        LoginPanel.setLayout(new java.awt.GridBagLayout());

        LoginPan.setBackground(new java.awt.Color(159, 82, 38));
        LoginPan.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 82, 38), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(159, 82, 38), 1, true)));
        LoginPan.setLayout(new java.awt.GridBagLayout());

        lblUsernameLogin.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lblUsernameLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblUsernameLogin.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 49, 0, 0);
        LoginPan.add(lblUsernameLogin, gridBagConstraints);

        tfPasswordLogin.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 51);
        LoginPan.add(tfPasswordLogin, gridBagConstraints);

        tfUsername.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 18, 0, 51);
        LoginPan.add(tfUsername, gridBagConstraints);

        btLogin2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btLogin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/Login/LoginButton.png"))); // NOI18N
        btLogin2.setContentAreaFilled(false);
        btLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 77, 12, 0);
        LoginPan.add(btLogin2, gridBagConstraints);

        lblPasswordLogin.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lblPasswordLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordLogin.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 55, 0, 0);
        LoginPan.add(lblPasswordLogin, gridBagConstraints);

        jButton6.setFont(btLogin2.getFont());
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/Login/ExitButton.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 112, 12, 51);
        LoginPan.add(jButton6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(407, 287, 0, 290);
        LoginPanel.add(LoginPan, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Powered By Sutandi, Mario & James");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(99, 368, 32, 0);
        LoginPanel.add(jLabel2, gridBagConstraints);

        SettingPanel.setBackground(new java.awt.Color(255, 73, 0));

        lbl_username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Nama Server");

        tfServer.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tfServer.setMaximumSize(new java.awt.Dimension(6, 25));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Port");

        tfPort.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        lbl_database.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_database.setForeground(new java.awt.Color(255, 255, 255));
        lbl_database.setText("Database");

        cbDatabase.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbDatabase.setMaximumSize(new java.awt.Dimension(50, 25));
        cbDatabase.setMinimumSize(new java.awt.Dimension(50, 25));
        cbDatabase.setPreferredSize(new java.awt.Dimension(50, 25));

        lbl_password.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_password.setText("Password");

        tfPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tfPassword.setMaximumSize(new java.awt.Dimension(6, 25));

        btConnect.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btConnect.setText("Connect");
        btConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnectActionPerformed(evt);
            }
        });

        btCancel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SettingPanelLayout = new javax.swing.GroupLayout(SettingPanel);
        SettingPanel.setLayout(SettingPanelLayout);
        SettingPanelLayout.setHorizontalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingPanelLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SettingPanelLayout.createSequentialGroup()
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SettingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SettingPanelLayout.createSequentialGroup()
                        .addComponent(lbl_database, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(cbDatabase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SettingPanelLayout.createSequentialGroup()
                        .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(tfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SettingPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );
        SettingPanelLayout.setVerticalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_database, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SISTEM INFORMASI RENTAL");
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPanel.setBackground(new java.awt.Color(255, 153, 0));
        MainPanel.setLayout(new java.awt.BorderLayout());

        NavPanel.setBackground(new java.awt.Color(236, 102, 0));
        NavPanel.setMinimumSize(new java.awt.Dimension(400, 85));
        NavPanel.setPreferredSize(new java.awt.Dimension(400, 75));

        btLogin.setBackground(new java.awt.Color(255, 153, 0));
        btLogin.setFont(new java.awt.Font("Alfa Slab One", 0, 14)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Logout");
        btLogin.setBorder(null);
        btLogin.setBorderPainted(false);
        btLogin.setMaximumSize(new java.awt.Dimension(70, 70));
        btLogin.setMinimumSize(new java.awt.Dimension(70, 70));
        btLogin.setPreferredSize(new java.awt.Dimension(70, 70));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        btPassword.setBackground(new java.awt.Color(255, 153, 0));
        btPassword.setFont(new java.awt.Font("Alfa Slab One", 0, 14)); // NOI18N
        btPassword.setForeground(new java.awt.Color(255, 255, 255));
        btPassword.setText("Password");
        btPassword.setBorder(null);
        btPassword.setBorderPainted(false);
        btPassword.setMaximumSize(new java.awt.Dimension(70, 70));
        btPassword.setMinimumSize(new java.awt.Dimension(70, 70));
        btPassword.setPreferredSize(new java.awt.Dimension(70, 70));
        btPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasswordActionPerformed(evt);
            }
        });

        btSetting.setBackground(new java.awt.Color(255, 153, 0));
        btSetting.setFont(new java.awt.Font("Alfa Slab One", 0, 14)); // NOI18N
        btSetting.setForeground(new java.awt.Color(255, 255, 255));
        btSetting.setText("Setting");
        btSetting.setBorder(null);
        btSetting.setBorderPainted(false);
        btSetting.setMaximumSize(new java.awt.Dimension(70, 70));
        btSetting.setMinimumSize(new java.awt.Dimension(70, 70));
        btSetting.setPreferredSize(new java.awt.Dimension(70, 70));
        btSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSettingActionPerformed(evt);
            }
        });

        btExit.setBackground(new java.awt.Color(255, 153, 0));
        btExit.setFont(new java.awt.Font("Alfa Slab One", 0, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("Exit");
        btExit.setBorder(null);
        btExit.setBorderPainted(false);
        btExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExit.setMaximumSize(new java.awt.Dimension(51, 25));
        btExit.setMinimumSize(new java.awt.Dimension(51, 25));
        btExit.setPreferredSize(new java.awt.Dimension(70, 70));
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btAbout.setBackground(new java.awt.Color(255, 153, 0));
        btAbout.setFont(new java.awt.Font("Alfa Slab One", 0, 14)); // NOI18N
        btAbout.setForeground(new java.awt.Color(255, 255, 255));
        btAbout.setText("About");
        btAbout.setBorder(null);
        btAbout.setBorderPainted(false);
        btAbout.setMaximumSize(new java.awt.Dimension(70, 70));
        btAbout.setMinimumSize(new java.awt.Dimension(70, 70));
        btAbout.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout NavPanelLayout = new javax.swing.GroupLayout(NavPanel);
        NavPanel.setLayout(NavPanelLayout);
        NavPanelLayout.setHorizontalGroup(
            NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        NavPanelLayout.setVerticalGroup(
            NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavPanelLayout.createSequentialGroup()
                .addGroup(NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        MainPanel.add(NavPanel, java.awt.BorderLayout.NORTH);

        BodyPanel.setBackground(new java.awt.Color(236, 102, 0));
        BodyPanel.setPreferredSize(new java.awt.Dimension(400, 30));

        LoadingBar.setMinimumSize(new java.awt.Dimension(10, 18));
        LoadingBar.setPreferredSize(new java.awt.Dimension(146, 18));

        lblUsername.setBackground(new java.awt.Color(204, 102, 0));
        lblUsername.setFont(new java.awt.Font("Alfa Slab One", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("username : ");

        username.setBackground(new java.awt.Color(204, 102, 0));
        username.setFont(new java.awt.Font("Alfa Slab One", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("a");

        lblDate.setFont(lblUsername.getFont());
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel3");

        lblTime.setFont(lblUsername.getFont());
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("jLabel3");

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username)
                .addGap(18, 18, 18)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(LoadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username)
                    .addComponent(lblDate)
                    .addComponent(lblTime))
                .addContainerGap())
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(LoadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(BodyPanel, java.awt.BorderLayout.SOUTH);

        ProgressPanel.setBackground(new java.awt.Color(255, 153, 0));
        ProgressPanel.setOpaque(false);
        ProgressPanel.setPreferredSize(new java.awt.Dimension(400, 223));
        ProgressPanel.setLayout(new java.awt.BorderLayout());

        MenuPanel.setBackground(new java.awt.Color(236, 102, 0));
        MenuPanel.setPreferredSize(new java.awt.Dimension(155, 240));
        MenuPanel.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/menu/1-01.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 5);
        MenuPanel.add(jButton1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/menu/2-01.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setMaximumSize(new java.awt.Dimension(323, 299));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = -13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 5);
        MenuPanel.add(jButton2, gridBagConstraints);

        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/menu/3-01.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 5);
        MenuPanel.add(jButton3, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/menu/5-01.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 65, 5);
        MenuPanel.add(jButton4, gridBagConstraints);

        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/menu/4-01.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 5);
        MenuPanel.add(jButton5, gridBagConstraints);

        ProgressPanel.add(MenuPanel, java.awt.BorderLayout.EAST);

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));
        jPanel5.setMaximumSize(new java.awt.Dimension(300, 32767));
        jPanel5.setOpaque(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.getViewport().setBorder(null);

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setForeground(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(tab);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        ProgressPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        MainPanel.add(ProgressPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        card.show(getContentPane(), "card");
    }//GEN-LAST:event_btLoginActionPerformed

    private void btPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasswordActionPerformed

    }//GEN-LAST:event_btPasswordActionPerformed

    private void btLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin2ActionPerformed
        login = AppUtil.getService().getByUsername(tfUsername.getText());
        if (login == null) {
            if (tfUsername.getText().equalsIgnoreCase("adminsir")) {
                login = AppUtil.getService().getLoginById(1);
                card.show(getContentPane(), "card2");
                username.setText("Administrator");
                tfUsername.setText("");
                tfPasswordLogin.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Username or password wrong");
            }

        } else if (login != null) {
            if (tfUsername.getText() != null && tfPasswordLogin.getText() != null && tfPasswordLogin.getText().equals(login.getPassword())) {
                card.show(getContentPane(), "card2");
                username.setText(tfUsername.getText());
                tfUsername.setText("");
                tfPasswordLogin.setText("");

            } else {
                JOptionPane.showMessageDialog(null, "Username or password wrong");
            }
        }


    }//GEN-LAST:event_btLogin2ActionPerformed

    private void btSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSettingActionPerformed
//        glasspane.showPanel(SettingPanel, new Dimension(500, 325));
//        glasspane.setVisible(true);
        new Support().NewTab(Main.getFrame().getTab(), new AccessList(), "Access List");
    }//GEN-LAST:event_btSettingActionPerformed

    private void btConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConnectActionPerformed

    }//GEN-LAST:event_btConnectActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        glasspane.setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new GarageList(), "Garage List");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new PeopleMenu(), "People Menu");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new RentList(), "Rent List");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new PurchaseMenu(), "Purchase Menu");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Support().NewTab(Main.getFrame().getTab(), new ReportMenu(), "Report Menu");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    public JTabbedPane getTab() {
        return tab;
    }

    public JProgressBar getLoadingBar() {
        return LoadingBar;
    }

    public GlassPanePanel getGlasspane() {
        return glasspane;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JPanel LoginPan;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel NavPanel;
    private javax.swing.JPanel ProgressPanel;
    private javax.swing.JPanel SettingPanel;
    private javax.swing.JButton btAbout;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btConnect;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btLogin2;
    private javax.swing.JButton btPassword;
    private javax.swing.JButton btSetting;
    private javax.swing.JComboBox<String> cbDatabase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPasswordLogin;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsernameLogin;
    private javax.swing.JLabel lbl_database;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JPasswordField tfPasswordLogin;
    private javax.swing.JTextField tfPort;
    private javax.swing.JTextField tfServer;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
