/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sumames.sir.ui.purchase;

import com.sumames.sir.Main;
import com.sumames.sir.entity.PurchaseRequest;
import com.sumames.sir.entity.PurchaseRequestDetail;
import com.sumames.sir.entity.Employer;
import com.sumames.sir.entity.PurchaseInvoice;
import com.sumames.sir.entity.PurchaseInvoiceDetail;
import com.sumames.sir.helper.AppUtil;
import com.sumames.sir.helper.AutoCompletion;
import com.sumames.sir.helper.Support;
import com.sumames.sir.ui.renderer.TableCellListener;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My pc
 */
public class PurchaseInvoiceData extends javax.swing.JPanel {

    private String option;
    private int recordId;
    private int prRecordId;
    private Action action;
    private HashMap<String, Integer> mapAccess;
    private PurchaseRequest purchaserequest;
    private Employer employe;
    private HashMap<String, Integer> requestno;
    private HashMap<String, Integer> employerID;
    private PurchaseRequestDetail requestdetail;
    private PurchaseInvoice purchaseInvoice;
    private PurchaseInvoiceDetail orderdetail;

    /**
     * Creates new form Purchase Request Input
     */
    public PurchaseInvoiceData(String option, int recordId) {
        this.option = option;
        this.recordId = recordId;
        initComponents();
        loadingData();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSave = new javax.swing.JButton();
        tfNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPurchaseInvoice = new javax.swing.JTable();
        btDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        dtDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        requestno = new HashMap();
        employerID = new HashMap();
        cbOrderNo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tfSubTotal = new javax.swing.JTextField();
        tfSupplierName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        tfDiscountValue = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfTaxPercent = new javax.swing.JTextField();
        tfTaxValue = new javax.swing.JTextField();
        tfDiscPercent = new javax.swing.JTextField();

        setFont(new java.awt.Font("Noto Serif", 0, 14)); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(844, 417));

        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/buttons/6-01.png"))); // NOI18N
        btSave.setBorderPainted(false);
        btSave.setContentAreaFilled(false);
        btSave.setPreferredSize(new java.awt.Dimension(65, 23));
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        tfNo.setFont(getFont());
        tfNo.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel6.setFont(getFont());
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No :");

        jLabel4.setFont(getFont());
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description :");

        jLabel1.setFont(getFont());
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date :");

        tbPurchaseInvoice.setFont(getFont());
        tbPurchaseInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record Id", "Description", "Price", "Qty", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KeyStroke keyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0);
        tbPurchaseInvoice.getActionMap().put("save", saveAction());
        tbPurchaseInvoice.getInputMap(JComponent.WHEN_FOCUSED).put(keyStroke, "save");

        action  = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                abstractActionPerformed(e);
            }
        };
        TableCellListener tcl = new TableCellListener(tbPurchaseInvoice, action);
        tbPurchaseInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbPurchaseInvoiceKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbPurchaseInvoice);
        if (tbPurchaseInvoice.getColumnModel().getColumnCount() > 0) {
            tbPurchaseInvoice.getColumnModel().getColumn(0).setMinWidth(0);
            tbPurchaseInvoice.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/buttons/4-01.png"))); // NOI18N
        btDelete.setBorder(null);
        btDelete.setContentAreaFilled(false);

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane1.setViewportView(taDescription);

        dtDate.setOpaque(false);
        dtDate.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel2.setFont(getFont());
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order No");

        cbOrderNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOrderNo.setPreferredSize(new java.awt.Dimension(100, 30));
        cbOrderNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOrderNoItemStateChanged(evt);
            }
        });
        cbOrderNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrderNoActionPerformed(evt);
            }
        });

        jLabel7.setFont(getFont());
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SubTotal :");

        tfSubTotal.setEditable(false);
        tfSubTotal.setFont(getFont());
        tfSubTotal.setEnabled(false);
        tfSubTotal.setPreferredSize(new java.awt.Dimension(100, 30));

        tfSupplierName.setFont(getFont());
        tfSupplierName.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel8.setFont(getFont());
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Supplier Name");

        jLabel9.setFont(getFont());
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total :");

        tfTotal.setEditable(false);
        tfTotal.setFont(getFont());
        tfTotal.setEnabled(false);
        tfTotal.setPreferredSize(new java.awt.Dimension(100, 30));

        tfDiscountValue.setFont(getFont());
        tfDiscountValue.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel10.setFont(getFont());
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Disc (%) :");

        jLabel11.setFont(getFont());
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tax (%) :");

        tfTaxPercent.setFont(getFont());
        tfTaxPercent.setPreferredSize(new java.awt.Dimension(100, 30));

        tfTaxValue.setFont(getFont());
        tfTaxValue.setPreferredSize(new java.awt.Dimension(100, 30));

        tfDiscPercent.setFont(getFont());
        tfDiscPercent.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfDiscPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfDiscountValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfTaxPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfTaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(573, 573, 573))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNo, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(dtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel7)
                                .addGap(201, 201, 201)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18)
                                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDelete)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbOrderNo, dtDate, tfNo, tfSubTotal, tfSupplierName, tfTotal});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel1)
                                    .addComponent(dtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel8)
                                    .addComponent(tfSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel7))
                                    .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfTaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfTaxPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfDiscPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbOrderNo, dtDate, tfNo, tfSubTotal, tfSupplierName, tfTotal});

    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        saveData();
    }//GEN-LAST:event_btSaveActionPerformed

    private void tbPurchaseInvoiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPurchaseInvoiceKeyPressed
        if (evt.getID() == KeyEvent.KEY_PRESSED) {
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                if (tbPurchaseInvoice.getSelectedRow() == tbPurchaseInvoice.getRowCount() - 1) {
                    addRow();
                }
            }
        }
    }//GEN-LAST:event_tbPurchaseInvoiceKeyPressed

    private void cbOrderNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrderNoActionPerformed
        if(requestno.get(cbOrderNo.getSelectedItem()) == null ){
            this.prRecordId = 0;
        }
        else
        this.prRecordId = requestno.get(cbOrderNo.getSelectedItem());
        refreshTable();
        count();
    }//GEN-LAST:event_cbOrderNoActionPerformed

    private void cbOrderNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOrderNoItemStateChanged
        refreshTable();
    }//GEN-LAST:event_cbOrderNoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbOrderNo;
    private com.toedter.calendar.JDateChooser dtDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTable tbPurchaseInvoice;
    private javax.swing.JTextField tfDiscPercent;
    private javax.swing.JTextField tfDiscountValue;
    private javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfSupplierName;
    private javax.swing.JTextField tfTaxPercent;
    private javax.swing.JTextField tfTaxValue;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
   private void saveData() {

        if (option.equals("NEW")) {
            formToObject();
            purchaseInvoice.setCreateDatetime(new Date());
            purchaseInvoice.setCreateByUserRecordId(Main.getFrame().getLogin().getEmployeeRecordId());
            if (AppUtil.getService().save(purchaseInvoice)) {
                for (int i = 0; i < tbPurchaseInvoice.getRowCount(); i++) {
                    PurchaseInvoiceDetail invoiceDetail = new PurchaseInvoiceDetail();
                    invoiceDetail.setPurchaseInvoiceRecordId(purchaseInvoice.getRecordId());
                    System.out.println(tbPurchaseInvoice.getValueAt(i, 2).toString());

                    invoiceDetail.setDescription(tbPurchaseInvoice.getValueAt(i, 1).toString());
                    invoiceDetail.setPrice(Double.parseDouble(tbPurchaseInvoice.getValueAt(i, 2).toString()));
                    invoiceDetail.setQty(Double.parseDouble(tbPurchaseInvoice.getValueAt(i, 3).toString()));
                    invoiceDetail.setSubtotal(Double.parseDouble(tbPurchaseInvoice.getValueAt(i, 4).toString()));
                    invoiceDetail.setCreateDatetime(new Date());
                    invoiceDetail.setCreateByUserRecordId(Main.getFrame().getLogin().getEmployeeRecordId());
                    AppUtil.getService().save(invoiceDetail);
                }
                msg("Save Done!");
                Main.getFrame().getTab().removeTabAt(Main.getFrame().getTab().getSelectedIndex());

            } else {
                msg("Save Failed!");
            }

        } else if (option.equals("EDIT")) {
            formToObject();
            System.out.println(recordId);
            purchaseInvoice.setRecordId(recordId);
            if (AppUtil.getService().save(purchaseInvoice)) {
                for (int i = 0; i < tbPurchaseInvoice.getRowCount(); i++) {
                    PurchaseInvoiceDetail invoiceDetail = new PurchaseInvoiceDetail();
                    if (tbPurchaseInvoice.getValueAt(i, 0) != null) {
                        invoiceDetail.setPurchaseInvoiceRecordId((Integer) tbPurchaseInvoice.getValueAt(i, 0));
                    }
                    invoiceDetail.setPurchaseInvoiceRecordId(recordId);
                    invoiceDetail.setDescription(tbPurchaseInvoice.getValueAt(i, 1).toString());
                    invoiceDetail.setPrice(Double.parseDouble(tbPurchaseInvoice.getValueAt(i, 2).toString()));
                    invoiceDetail.setQty(Double.parseDouble(tbPurchaseInvoice.getValueAt(i, 3).toString()));
                    invoiceDetail.setSubtotal(Double.parseDouble(tbPurchaseInvoice.getValueAt(i, 4).toString()));
                    invoiceDetail.setCreateDatetime(new Date());
                    invoiceDetail.setCreateByUserRecordId(Main.getFrame().getLogin().getEmployeeRecordId());
                    AppUtil.getService().save(invoiceDetail);
                }
                msg("Save Done!");
                Main.getFrame().getTab().removeTabAt(Main.getFrame().getTab().getSelectedIndex());
            } else {
                msg("Save Failed!");
            }
        }
    }

    public void formToObject() {
        if (purchaseInvoice == null) {
            purchaseInvoice = new PurchaseInvoice();
        }
        purchaseInvoice.setNo(tfNo.getText());
        purchaseInvoice.setDate(dtDate.getDate());
        purchaseInvoice.setPurchaseOrderRecordId(requestno.get(cbOrderNo.getSelectedItem()));
        purchaseInvoice.setNote(taDescription.getText());
//        Invoicedetail.setPurchaseInvoiceRecordId(Integer.parseInt(cbrequestno.getSelectedItem().toString()));
        purchaseInvoice.setTotal(Double.parseDouble(tfSubTotal.getText()));
        purchaseInvoice.setNote(taDescription.getText());
    }

    public void objectToForm() {
        if (purchaseInvoice != null) {
            tfNo.setText(purchaseInvoice.getNo());
            dtDate.setDate(purchaseInvoice.getDate());
            cbOrderNo.setSelectedItem(Support.getKeyFromValue(requestno, purchaseInvoice.getPurchaseOrderRecordId()));
            tfSubTotal.setText(purchaseInvoice.getTotal().toString());
            taDescription.setText(purchaseInvoice.getNote());

        }
    }

    private void abstractActionPerformed(java.awt.event.ActionEvent evt) {
        TableCellListener tcl = (TableCellListener) evt.getSource();
        int row = tbPurchaseInvoice.getSelectedRow();
        if (tbPurchaseInvoice.getSelectedRow() >= 0) {
            switch (tcl.getColumn()) {
                case 2: {
                    int a;
                    if (tbPurchaseInvoice.getModel().getValueAt(row, 3) == null) {
                        a = 0;
                    } else {
                        a = Integer.parseInt(tbPurchaseInvoice.getModel().getValueAt(row, 3).toString());
                    }
                    Double b = (Double) tcl.getNewValue();
                    Double subtotal = a * b;
                    tbPurchaseInvoice.setValueAt(subtotal, row, 4);
                    count();
                    break;
                }
                case 3: {
                    double a;
                    if (tbPurchaseInvoice.getModel().getValueAt(row, 2) == null) {
                        a = 0.00;
                    } else {
                        a = Double.parseDouble(String.valueOf(tbPurchaseInvoice.getModel().getValueAt(row, 2)));
                    }
                    int b = Integer.parseInt(tcl.getNewValue().toString());
                    double subtotal = a * b;
                    tbPurchaseInvoice.setValueAt(subtotal, row, 4);
                    count();
                    break;
                }
                default:
                    break;
            }

        }
    }

    private AbstractAction saveAction() {
        AbstractAction save = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
//                JOptionPane.showMessageDialog(RentData.this.tbRent, "Action Triggered.");
                tbPurchaseInvoice.editingCanceled(null);
                tbPurchaseInvoice.editingStopped(null);
                int selectedRow = tbPurchaseInvoice.getSelectedRow();
                if (selectedRow != -1) {
                    ((DefaultTableModel) tbPurchaseInvoice.getModel()).removeRow(selectedRow);
                    tbPurchaseInvoice.scrollRectToVisible(tbPurchaseInvoice.getCellRect(tbPurchaseInvoice.getRowCount() - 1, 0, true));
                }
            }
        };
        return save;
    }

    private void addRow() {
        DefaultTableModel model = (DefaultTableModel) tbPurchaseInvoice.getModel();
        if (model != null) {
            model.addRow(new Object[]{});
        }

    }

    public void refreshTable() {
        List<PurchaseRequestDetail> list = AppUtil.getService().getListRequestDetailById(prRecordId);
        DefaultTableModel dtm = (DefaultTableModel) tbPurchaseInvoice.getModel();
        dtm.setRowCount(0);
        for (PurchaseRequestDetail rd : list) {
            dtm.addRow(new Object[]{rd.getRecordId(), rd.getDescription(), rd.getEstPrice(), rd.getQty(), rd.getSubtotal()});
        }
    }

    public void count() {
        if (tbPurchaseInvoice.getRowCount() > 0) {
            Double subtotal = 0.00;

            for (int i = 0; i <= tbPurchaseInvoice.getRowCount() - 1; i++) {
                System.out.println("Value = " + tbPurchaseInvoice.getModel().getValueAt(i, 4));
                subtotal = subtotal + Double.parseDouble(tbPurchaseInvoice.getModel().getValueAt(i, 4).toString());
                System.out.println("Subtotal" + subtotal);
            }
            tfSubTotal.setText(subtotal.toString());
        }
    }

    public void loadingData() {
        cbOrderNo.removeAllItems();
        AutoCompletion.enable(cbOrderNo);
        addRow();
        
        List<PurchaseRequest> requestlist = AppUtil.getService().getRequest();
        for (PurchaseRequest request : requestlist) {
            requestno.put(request.getNo(), request.getRecordId());
            cbOrderNo.addItem(request.getNo());
        }
        List<Employer> employerlist = AppUtil.getService().getEmployersNotDeleted();
        for (Employer employe : employerlist) {
            employerID.put(employe.getName(), employe.getRecordId());

        }
        if (option.equals("NEW")) {
            tfNo.setText("");
            tfSubTotal.setText("0");
            taDescription.setText("");
            dtDate.setDate(new Date());
        } else if (option.equals("EDIT")) {
            purchaseInvoice = AppUtil.getService().getInvoiceById(recordId);
            objectToForm();
            refreshTable();
        }
    }

    private void msg(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
}
