package com.sumames.sir.ui.purchase;

import com.sumames.sir.ui.MainFrame;
import com.sumames.sir.helper.Support;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sutandi
 */
public class PurchaseMenu extends javax.swing.JPanel {
    private MainFrame m;
    /**
     * Creates new form PeopleMenu
     */
    public PurchaseMenu(MainFrame m) {
        this.m = m;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btRequest = new javax.swing.JButton();
        btOrder = new javax.swing.JButton();
        btPayment = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        btRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/purchase/1-01-01.png"))); // NOI18N
        btRequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btRequest.setContentAreaFilled(false);
        btRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRequestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRequestMouseExited(evt);
            }
        });
        btRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRequestActionPerformed(evt);
            }
        });
        jPanel1.add(btRequest);

        btOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/purchase/2-01-01.png"))); // NOI18N
        btOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btOrder.setContentAreaFilled(false);
        btOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btOrderMouseExited(evt);
            }
        });
        btOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btOrder);

        add(jPanel1);

        btPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sumames/sir/resources/image/purchase/3-01.png"))); // NOI18N
        btPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btPayment.setContentAreaFilled(false);
        btPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPaymentMouseExited(evt);
            }
        });
        btPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPaymentActionPerformed(evt);
            }
        });
        add(btPayment);
    }// </editor-fold>//GEN-END:initComponents

    private void btOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOrderMouseEntered
        btOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btOrderMouseEntered

    private void btOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btOrderMouseExited
        btOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btOrderMouseExited

    private void btPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaymentMouseEntered
        btPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btPaymentMouseEntered

    private void btPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaymentMouseExited
        btPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btPaymentMouseExited

    private void btOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrderActionPerformed
        new Support().NewTab(m.getTab(), new PurchaseOrderList(m), "Order List");
    }//GEN-LAST:event_btOrderActionPerformed

    private void btPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPaymentActionPerformed
        new Support().NewTab(m.getTab(), new PurchasePaymentList(m), "Payment List");
    }//GEN-LAST:event_btPaymentActionPerformed

    private void btRequestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRequestMouseEntered
        btRequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 90, 43), 4));
    }//GEN-LAST:event_btRequestMouseEntered

    private void btRequestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRequestMouseExited
        btRequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_btRequestMouseExited

    private void btRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRequestActionPerformed
        new Support().NewTab(m.getTab(), new PurchaseRequestList(m), "Request List");
    }//GEN-LAST:event_btRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOrder;
    private javax.swing.JButton btPayment;
    private javax.swing.JButton btRequest;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
